---
services:
  - gluetun
  - deluge
  - nzbget

nfs_mounts:
  - src: 192.168.1.80:/volume1/downloads
    path: /mnt/downloads
    opts: rw,nfsvers=4.1
  - src: 192.168.1.80:/volume1/media
    path: /mnt/media
    opts: rw,nfsvers=4.1

vpn_provider: nordvpn
vpn_tunnel: wireguard
vpn_kill_switch_enabled: true
vpn_namespace_container: gluetun
