all:
  children:
    proxmox:
      hosts:
        infinity-node:
          ansible_host: 192.168.1.81
          ansible_user: root

    docker_hosts:
      hosts:
        emby:
          ansible_host: vm-100.local.infinity-node.win
          ansible_user: coda
          vm_id: 100
        downloads:
          ansible_host: vm-101.local.infinity-node.win
          ansible_user: coda
          vm_id: 101
        arr:
          ansible_host: vm-102.local.infinity-node.win
          ansible_user: coda
          vm_id: 102
        misc:
          ansible_host: vm-103.local.infinity-node.win
          ansible_user: coda
          vm_id: 103
        openclaw:
          ansible_host: localhost
          ansible_user: coda
          ansible_connection: local
          vm_id: 104

    infrastructure:
      hosts:
        pihole:
          ansible_host: 192.168.1.79
        synology:
          ansible_host: 192.168.1.80
          ansible_connection: local
